services:
  - type: web
    name: dsa-tracker
    runtime: node
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /var/data
    disk:
      name: dsa-data
      mountPath: /var/data
      sizeGB: 1
